### ISSUE TITLE
Get general information from user account

### ISSUE THREAD

**Issue by masmerino13** [IDme/PHP-sample-code#1]
We have a API who use your ID.me android SDK, we need to auto-signup the users in our platform if they are valid ID.me users, for that we need some general information (First/Last name).

It's possible get general information from one user using their email or some other param?

**Comment by tonycchung** [comment]
Hey @masmerino13 sorry for the delay in response, was not aware of your posted issue here..

If you refer to our documentation [here](https://developer.id.me/documentation) under the "REST API Endpoints" section you can see that our attributes API endpoint will return various attributes of the user including first and last name.

**Comment by tonycchung** [comment]
Hey @masmerino13!

If you refer to our documentation [here](https://developer.id.me/documentation) under the "REST API Endpoints" section you can see that our attributes API endpoint will return various attributes of the user including first and last name based on the policy we set up for your application.

Feel free to get in touch with partnersupport@id.me for any further questions you may have!
